import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { pinoHttp } from 'pino-http';
import { env } from './config/env.js';
import { errorHandler } from './middleware/error-handler.js';
import { authRouter } from './routes/auth.js';
import { clientRouter } from './routes/clients.js';
import { healthRouter } from './routes/health.js';
import { platformRouter } from './routes/platform.js';
import { brandRouter } from './routes/brands.js';
import { projectRouter } from './routes/projects.js';
import { dashboardRouter } from './routes/dashboard.js';
import { catalogRouter } from './routes/catalog.js';
import { measurementRouter } from './routes/measurements.js';
import { calculationRouter } from './routes/calculations.js';
import { quoteRouter } from './routes/quotes.js';
import { operationsRouter } from './routes/operations.js';
import { organizationRouter } from './routes/organization.js';
import { requireAuth } from './middleware/auth.js';
import { idempotency } from './middleware/idempotency.js';
import { customizationRouter } from './routes/customization.js';
import { costingRouter } from './routes/costing.js';
import { serviceRouter } from './routes/service.js';
export const app = express();

app.use(helmet());
app.use(cors({ origin: env.WEB_ORIGIN, credentials: true }));
app.use(express.json({ limit: '1mb' }));
if (env.NODE_ENV !== 'test') app.use(pinoHttp());

app.get('/', (_request, response) => response.json({ name: 'Avin Business Suite API', version: '0.1.0' }));
app.use('/api/v1/health', healthRouter);
app.use('/api/v1/platform', platformRouter);
app.use('/api/v1/auth', authRouter);
const protectedRouter = express.Router();
protectedRouter.use(requireAuth, idempotency);
protectedRouter.use('/clients', clientRouter);
protectedRouter.use('/brands', brandRouter);
protectedRouter.use('/projects', projectRouter);
protectedRouter.use('/dashboard', dashboardRouter);
protectedRouter.use('/catalog', catalogRouter);
protectedRouter.use('/measurements', measurementRouter);
protectedRouter.use('/calculations', calculationRouter);
protectedRouter.use('/quotes', quoteRouter);
protectedRouter.use('/operations', operationsRouter);
protectedRouter.use('/organization', organizationRouter);
protectedRouter.use('/customization', customizationRouter);
protectedRouter.use('/costing', costingRouter);
protectedRouter.use('/service', serviceRouter);
app.use('/api/v1', protectedRouter);

app.use((_request, response) => response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Route not found' } }));
app.use(errorHandler);
