import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Bell, FileUp, Share2 } from 'lucide-react';
import { apiBaseUrl, apiRequest } from '../lib/api';

type Project = { _id: string; projectNumber: string; name: string };
type Attachment = { _id: string; fileName: string; mimeType: string; size: number; category: string; createdAt: string };
type Notification = { _id: string; title: string; message: string; readAt?: string; createdAt: string };
type Preferences = { inApp: boolean; email: boolean; whatsapp: boolean; paymentReminders: boolean; followUpReminders: boolean; serviceReminders: boolean };

export function FilesNotifications() {
  const [projects, setProjects] = useState<Project[]>([]); const [attachments, setAttachments] = useState<Attachment[]>([]); const [notifications, setNotifications] = useState<Notification[]>([]); const [preferences, setPreferences] = useState<Preferences | null>(null); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const [p, a, n, prefs] = await Promise.all([apiRequest<Project[]>('/projects'), apiRequest<Attachment[]>('/files/attachments'), apiRequest<Notification[]>('/files/notifications'), apiRequest<Preferences>('/files/preferences')]); setProjects(p); setAttachments(a); setNotifications(n); setPreferences(prefs); }, []);
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : 'Unable to load files')); }, [load]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const file = data.get('file') as File; if (!file?.size) return; if (file.size > 5 * 1024 * 1024) throw new Error('File must be smaller than 5 MB'); const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] ?? ''); reader.onerror = reject; reader.readAsDataURL(file); }); await apiRequest('/files/attachments', { method: 'POST', body: JSON.stringify({ entityType: 'project', entityId: data.get('entityId'), category: data.get('category'), fileName: file.name, mimeType: file.type, dataBase64: base64, description: data.get('description') }) }); form.reset(); setMessage('File uploaded securely.'); await load(); }
  async function savePreferences(next: Preferences) { setPreferences(next); await apiRequest('/files/preferences', { method: 'PUT', body: JSON.stringify(next) }); setMessage('Notification preferences saved.'); }
  async function createShare(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await apiRequest<{ url: string }>('/files/share-links', { method: 'POST', body: JSON.stringify({ channel: data.get('channel'), phone: data.get('phone') || undefined, email: data.get('email') || undefined, subject: data.get('subject'), message: data.get('message') }) }); window.open(result.url, '_blank', 'noopener,noreferrer'); }
  const token = localStorage.getItem('avin_token');
  return <div className="space-y-6">{message && <div className="rounded-xl bg-brand-50 px-4 py-3 text-sm font-bold text-brand-800">{message}</div>}<div className="grid gap-5 xl:grid-cols-2">
    <form onSubmit={(event) => void upload(event).catch((error) => setMessage(error.message))} className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="flex items-center gap-2 text-lg font-black"><FileUp size={20}/> Upload project file or photo</h2><div className="mt-4 grid gap-3"><select name="entityId" required className="rounded-xl border p-3"><option value="">Select project</option>{projects.map((project) => <option key={project._id} value={project._id}>{project.projectNumber} — {project.name}</option>)}</select><select name="category" className="rounded-xl border p-3"><option value="document">Document</option><option value="site_photo">Site photo</option><option value="measurement_photo">Measurement photo</option><option value="delivery_proof">Delivery proof</option><option value="installation_proof">Installation proof</option></select><input name="file" type="file" required accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,text/csv" className="rounded-xl border p-3"/><input name="description" placeholder="Description" className="rounded-xl border p-3"/></div><button className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Upload securely</button></form>
    <form onSubmit={(event) => void createShare(event).catch((error) => setMessage(error.message))} className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="flex items-center gap-2 text-lg font-black"><Share2 size={20}/> Share by WhatsApp or email</h2><div className="mt-4 grid gap-3"><select name="channel" className="rounded-xl border p-3"><option value="whatsapp">WhatsApp</option><option value="email">Email</option></select><input name="phone" placeholder="WhatsApp number with country code" className="rounded-xl border p-3"/><input name="email" type="email" placeholder="Email address" className="rounded-xl border p-3"/><input name="subject" defaultValue="Project update" className="rounded-xl border p-3"/><textarea name="message" required placeholder="Message" className="min-h-24 rounded-xl border p-3"/></div><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Open sharing app</button></form>
  </div>
  <section className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="text-lg font-black">Files and proof</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{attachments.map((file) => <a key={file._id} href={`${apiBaseUrl}/files/attachments/${file._id}/content`} onClick={(event) => { event.preventDefault(); void fetch(event.currentTarget.href, { headers: token ? { Authorization: `Bearer ${token}` } : {}, credentials: 'include' }).then((r) => r.blob()).then((blob) => window.open(URL.createObjectURL(blob), '_blank')); }} className="rounded-xl border p-4 hover:border-brand-400"><b className="block truncate">{file.fileName}</b><span className="text-xs text-slate-500">{file.category} · {(file.size / 1024).toFixed(1)} KB</span></a>)}</div></section>
  {preferences && <section className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="flex items-center gap-2 text-lg font-black"><Bell size={20}/> Notification preferences</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(preferences).filter(([,value]) => typeof value === 'boolean').map(([key, value]) => <label key={key} className="flex items-center gap-3 rounded-xl border p-3 text-sm font-bold"><input type="checkbox" checked={Boolean(value)} onChange={(event) => void savePreferences({ ...preferences, [key]: event.target.checked })}/>{key.replace(/([A-Z])/g, ' $1')}</label>)}</div></section>}
  <section className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="text-lg font-black">Notification centre</h2><div className="mt-4 space-y-2">{notifications.length ? notifications.map((item) => <button key={item._id} onClick={() => void apiRequest(`/files/notifications/${item._id}/read`, { method: 'PATCH' }).then(load)} className={`block w-full rounded-xl p-4 text-left ${item.readAt ? 'bg-slate-50' : 'bg-brand-50'}`}><b>{item.title}</b><p className="mt-1 text-sm text-slate-600">{item.message}</p></button>) : <p className="text-sm text-slate-500">No notifications.</p>}</div></section></div>;
}
