import { SaveForm } from './SaveForm';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Download, LockKeyhole, ShieldCheck } from 'lucide-react';
import { apiRequest } from '../lib/api';

type Event = { _id: string; type: string; severity: string; success: boolean; description: string; createdAt: string; userId?: { name: string } };
type Audit = { _id: string; action: string; description: string; recordHash?: string; createdAt: string; userId?: { name: string } };

export function SecurityCenter() {
  const [events, setEvents] = useState<Event[]>([]); const [audit, setAudit] = useState<Audit[]>([]); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const [e, a] = await Promise.all([apiRequest<Event[]>('/security/events'), apiRequest<Audit[]>('/security/audit')]); setEvents(e); setAudit(a); }, []);
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : 'Security reports require administrator access')); }, [load]);
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); if (data.get('newPassword') !== data.get('confirmation')) throw new Error('New passwords do not match'); await apiRequest('/auth/change-password', { method: 'POST', body: JSON.stringify({ currentPassword: data.get('currentPassword'), newPassword: data.get('newPassword') }) }); form.reset(); setMessage('Password changed. Existing refresh sessions should be signed out manually on shared devices.'); }
  async function exportData() { const data = await apiRequest<unknown>('/security/export'); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `avin-export-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url); }
  return <div className="space-y-6">{message && <div className="rounded-xl bg-brand-50 px-4 py-3 text-sm font-bold text-brand-800">{message}</div>}<div className="grid gap-5 xl:grid-cols-2"><SaveForm onSubmit={changePassword} className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="flex items-center gap-2 text-lg font-black"><LockKeyhole size={20}/> Change password</h2><div className="mt-4 grid gap-3"><input name="currentPassword" type="password" required placeholder="Current password" className="rounded-xl border p-3"/><input name="newPassword" type="password" required minLength={10} placeholder="New password (10+ characters)" className="rounded-xl border p-3"/><input name="confirmation" type="password" required minLength={10} placeholder="Confirm new password" className="rounded-xl border p-3"/></div><button className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Change password</button></SaveForm><section className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="flex items-center gap-2 text-lg font-black"><ShieldCheck size={20}/> Security controls</h2><ul className="mt-4 space-y-2 text-sm text-slate-600"><li>✓ 15-minute access tokens with rotating refresh sessions</li><li>✓ Login and API rate limiting</li><li>✓ Password recovery invalidates existing sessions</li><li>✓ Automatic audit records for successful mutations</li><li>✓ Security-event retention for one year</li></ul><button onClick={() => void exportData().catch((error) => setMessage(error.message))} className="mt-5 flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-3 text-sm font-bold text-white"><Download size={17}/> Export organization data</button></section></div>
  <section className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="text-lg font-black">Security events</h2><div className="mt-4 space-y-2">{events.map((item) => <div key={item._id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{item.type}</b> · {item.success ? 'Success' : 'Failed'} · {item.description}<span className="ml-2 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</span></div>)}</div></section>
  <section className="rounded-2xl border bg-white p-5 shadow-card"><h2 className="text-lg font-black">Immutable audit chain</h2><div className="mt-4 max-h-96 space-y-2 overflow-auto">{audit.map((item) => <div key={item._id} className="rounded-xl border p-3 text-sm"><b>{item.action}</b> · {item.description}<div className="mt-1 truncate font-mono text-[10px] text-slate-400">{item.recordHash ?? 'legacy record'}</div></div>)}</div></section></div>;
}
